# Generated by Django 4.0.5 on 2022-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('backlink', models.URLField(blank=True, max_length=150)),
                ('linkname', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(max_length=2500)),
                ('subtitleone', models.CharField(blank=True, max_length=500)),
                ('subphotoone', models.ImageField(blank=True, upload_to='myimage')),
                ('subdescone', models.CharField(blank=True, max_length=2500)),
                ('subtitletwo', models.CharField(blank=True, max_length=500)),
                ('subphototwo', models.ImageField(blank=True, upload_to='myimage')),
                ('subdesctwo', models.CharField(blank=True, max_length=2500)),
                ('subtitlethree', models.CharField(blank=True, max_length=500)),
                ('subphotothree', models.ImageField(blank=True, upload_to='myimage')),
                ('subdescthree', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Makemoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('backlink', models.URLField(blank=True, max_length=150)),
                ('linkname', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(max_length=2500)),
                ('subtitleone', models.CharField(blank=True, max_length=500)),
                ('subphotoone', models.ImageField(blank=True, upload_to='myimage')),
                ('subdescone', models.CharField(blank=True, max_length=2500)),
                ('subtitletwo', models.CharField(blank=True, max_length=500)),
                ('subphototwo', models.ImageField(blank=True, upload_to='myimage')),
                ('subdesctwo', models.CharField(blank=True, max_length=2500)),
                ('subtitlethree', models.CharField(blank=True, max_length=500)),
                ('subphotothree', models.ImageField(blank=True, upload_to='myimage')),
                ('subdescthree', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('backlink', models.URLField(blank=True, max_length=150)),
                ('linkname', models.CharField(blank=True, max_length=150)),
                ('desc', models.CharField(max_length=2500)),
                ('subtitleone', models.CharField(blank=True, max_length=500)),
                ('subphotoone', models.ImageField(blank=True, upload_to='myimage')),
                ('subdescone', models.CharField(blank=True, max_length=2500)),
                ('subtitletwo', models.CharField(blank=True, max_length=500)),
                ('subphototwo', models.ImageField(blank=True, upload_to='myimage')),
                ('subdesctwo', models.CharField(blank=True, max_length=2500)),
                ('subtitlethree', models.CharField(blank=True, max_length=500)),
                ('subphotothree', models.ImageField(blank=True, upload_to='myimage')),
                ('subdescthree', models.CharField(blank=True, max_length=2500)),
            ],
        ),
    ]
