# Generated by Django 4.0.5 on 2022-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='desc',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='subdescone',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='subdescthree',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='subdesctwo',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='makemoney',
            name='desc',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='makemoney',
            name='subdescone',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='makemoney',
            name='subdescthree',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='makemoney',
            name='subdesctwo',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='technology',
            name='desc',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='technology',
            name='subdescone',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='technology',
            name='subdescthree',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='technology',
            name='subdesctwo',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
